language: c
compiler:
  - gcc
  - clang

# Requring sudo as a work around for https://github.com/travis-ci/travis-ci/issues/8082
sudo: false
dist: trusty

addons:
  apt:
    packages:
      - autoconf-archive
      - dbus
      - dbus-x11
      - cmake
      - lcov
      - libglib2.0-dev
      - libdbus-1-dev
      - liburiparser-dev
      - realpath
  coverity_scan:
    project:
      name: 01org/tpm2-abrmd
      description: Build submitted via Travis-CI
    notification_email: flihp@twobit.us
    build_command_prepend: "./configure; make clean"
    build_command: "make -j$(nproc)"
    branch_pattern: coverity_scan

env:
  global:
    # COVERITY_SCAN_TOKEN created by coverity using 'travis encrypt' using
    # project repo public key
    - secure: "i7rPPY1dLPo6Uaa9DzIadMOYSoRV9Vp+6OJQogbcaBTGx9jvZT4lhO+K4Fe/SW5uqSq9gtRKWNgj/FpWhOKIzLi6AS7B9UemZ5h5KBnwU/NM1ANSjEdbJ8RyhZ+Ito8Q3WMrL+kXpiQf2CpTwp92BLVfW4txCaRFKLpYetSknM52p5MEn/y5LtojTrRdI7gAsCribbaK4bK9nDqHr4XilC1A7NWIcRR4h2UvyVIbMY2qV17PiO7VI6F2roNXvW/0tBi//ezjqAhby8DkyEbehCWDSePc6CpDGKSfe572wANVgLAgriWaMpPl0sHxVNBa2HHZekP4F70sbRgPVZoge8QrXJoU2xsn/GghJGQh9Gx02jHOs5ijusa9XgzyR43M3z+HH0wqcBWzxVSWXbugGRcvQvXehuBVWUEDtPIZTjxp6NGmQe43saVCZmk2+l353jbdlbjpxu9MPpZK5H+guEVBRh1fh8h0vtCLLQxnRR/ufyvHhRLg7w4uVGqyX5twC4h/G+UyP2kGJHsixeiID1mc/pjp2xQguOUUCfmu9sOANgb8jGQ0dcKJ5EDjNEzi1Y5plD/BcffFRpS92I9lZA+1BXJS65ZM64a4oMnHK5ckKBu8ilNtZvYqlR3pWWW5bgPV67JuKLp9IrVNgc9NgxjmNmSOtqYN17lobkTUfK8="
    # run coverity scan on gcc build to keep from DOSing coverity
    - coverity_scan_run_condition='"$CC" = gcc'
    - PREFIX=/usr
    - DEPS="${TRAVIS_BUILD_DIR}/deps"
    - DESTDIR="${TRAVIS_BUILD_DIR}/destdir"
    - ACLOCAL_PATH="${DESTDIR}${PREFIX}/share/aclocal:${ACLOCAL_PATH}"
    - PKG_CONFIG_PATH="${DESTDIR}${PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH}"
    - LD_LIBRARY_PATH="${DESTDIR}${PREFIX}/lib:${LD_LIBRARY_PATH}"
    - CFLAGS="-I${DESTDIR}${PREFIX}/include"
    - CMOCKA_LIBS="-L${DESTDIR}${PREFIX}/lib -lcmocka"

install:
  - pip install --user cpp-coveralls
  - mkdir ${DESTDIR} ${DEPS} && pushd ${DEPS}
  - wget http://ftpmirror.gnu.org/autoconf-archive/autoconf-archive-2017.09.28.tar.xz
  - sha256sum autoconf-archive-2017.09.28.tar.xz | grep -q 5c9fb5845b38b28982a3ef12836f76b35f46799ef4a2e46b48e2bd3c6182fa01
  - tar xJf autoconf-archive-2017.09.28.tar.xz && pushd autoconf-archive-2017.09.28
  - ./configure --prefix=${PREFIX} && make && make install
  - popd # autoconf-archive
  - wget https://cmocka.org/files/1.1/cmocka-1.1.1.tar.xz
  - tar -Jxvf cmocka-1.1.1.tar.xz
  - mkdir cmocka-1.1.1/build && pushd cmocka-1.1.1/build
  - cmake ../ -DCMAKE_INSTALL_PREFIX=${PREFIX} -DCMAKE_BUILD_TYPE=Release
  - make -j$(nproc) install
  - popd # cmocka
  - git clone -b master --single-branch https://github.com/01org/tpm2-tss.git
  - pushd tpm2-tss
  - ./bootstrap
  - ./configure --prefix=${PREFIX}
  - make -j$(nproc) install
  - popd # tpm2-tss
  - sed -i -e "s&\(\/usr\/lib\/lib.*\.la\)&${DESTDIR}\1&" ${DESTDIR}${PREFIX}/lib/*.la
  - wget https://downloads.sourceforge.net/project/ibmswtpm2/ibmtpm974.tar.gz
  - sha256sum ibmtpm974.tar.gz | grep -q ^8e45d86129a0adb95fee4cee51f4b1e5b2d81ed3e55af875df53f98f39eb7ad7
  - mkdir ibmtpm
  - tar axf ibmtpm974.tar.gz -C ibmtpm
  - make -C ibmtpm/src -j$(nproc)
  - popd # ${DEPS}

before_script:
  - ./bootstrap

script :
  - echo 'Configuring source code...' && echo -en 'travis_fold:start:tabrmd-configure\\r'
  - |
    CONFIGURE_OPTIONS="--disable-dlclose --enable-unit --with-simulatorbin=${DEPS}/ibmtpm/src/tpm_server"
    if [ "$CC" = "gcc" ]; then
        CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS --enable-code-coverage"
    fi
    ./configure ${CONFIGURE_OPTIONS}
  - echo -en 'travis_fold:end:tabrmd-configure\\r'
  - echo "Running make 'distcheck' target..." && echo -en 'travis_fold:start:tabrmd-distcheck\\r'
  - dbus-launch make -j$(nproc) distcheck
  - echo -en 'travis_fold:end:tabrmd-distcheck\\r'
  - echo "Running make 'check-code-coverage' target..." && echo -en 'travis_fold:start:tabrmd-check-code-coverage\\r'
  - dbus-launch make -j$(nproc) check-code-coverage
  - |
    if [ \( "$CC" = "gcc" \) -a \( ! -z "$COVERALLS_REPO_TOKEN" \) ]; then
        echo "Uploading test coverage metrics to coveralls."
        coveralls --build-root=./ --exclude=${DEPS} --exclude=${DESTDIR} --exclude=./test --exclude=tpm2-abrmd-$(cat VERSION) --exclude=./coverity --exclude=./src/tabrmd-generated.c --exclude=./src/tabrmd-generated.h --gcov-options '\-lp'
    fi
  - echo -en 'travis_fold:end:tabrmd-check-code-coverage\\r'
  - echo 'Dumping unit test logs...' && echo -en 'travis_fold:start:tabrmd-unit-logs\\r'
  - |
    cat test-suite*.log
    for LOG in $(ls -1 test/*.log); do
        echo "${LOG}"
        cat ${LOG}
    done
  - echo -en 'travis_fold:end:tabrmd-unit-logs\\r'
